using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CouchTwitch
{
    // Generated by Xamasoft JSON Class Generator
    // http://www.xamasoft.com/json-class-generator

    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;

    namespace CouchTwitch
    {

        internal class AuthToken
        {

            [JsonProperty("token")]
            public string Token { get; set; }

            [JsonProperty("sig")]
            public string Sig { get; set; }

            [JsonProperty("mobile_restricted")]
            public bool MobileRestricted { get; set; }
        }

    }

}
