using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CouchTwitch
{
    // Generated by Xamasoft JSON Class Generator
    // http://www.xamasoft.com/json-class-generator

    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using CouchTwitch.FollowsJsonTypes;

    namespace CouchTwitch.FollowsJsonTypes
    {

        internal class Links
        {

            [JsonProperty("self")]
            public string Self { get; set; }
        }

        internal class Links2
        {

            [JsonProperty("self")]
            public string Self { get; set; }

            [JsonProperty("follows")]
            public string Follows { get; set; }

            [JsonProperty("commercial")]
            public string Commercial { get; set; }

            [JsonProperty("stream_key")]
            public string StreamKey { get; set; }

            [JsonProperty("chat")]
            public string Chat { get; set; }

            [JsonProperty("features")]
            public string Features { get; set; }

            [JsonProperty("subscriptions")]
            public string Subscriptions { get; set; }

            [JsonProperty("editors")]
            public string Editors { get; set; }

            [JsonProperty("videos")]
            public string Videos { get; set; }

            [JsonProperty("teams")]
            public string Teams { get; set; }
        }

        internal class Channel
        {

            [JsonProperty("_links")]
            public Links2 Links { get; set; }

            [JsonProperty("background")]
            public object Background { get; set; }

            [JsonProperty("banner")]
            public object Banner { get; set; }

            [JsonProperty("broadcaster_language")]
            public string BroadcasterLanguage { get; set; }

            [JsonProperty("display_name")]
            public string DisplayName { get; set; }

            [JsonProperty("game")]
            public string Game { get; set; }

            [JsonProperty("logo")]
            public string Logo { get; set; }

            [JsonProperty("mature")]
            public bool Mature { get; set; }

            [JsonProperty("status")]
            public string Status { get; set; }

            [JsonProperty("partner")]
            public bool Partner { get; set; }

            [JsonProperty("url")]
            public string Url { get; set; }

            [JsonProperty("video_banner")]
            public string VideoBanner { get; set; }

            [JsonProperty("_id")]
            public int Id { get; set; }

            [JsonProperty("name")]
            public string Name { get; set; }

            [JsonProperty("created_at")]
            public string CreatedAt { get; set; }

            [JsonProperty("updated_at")]
            public string UpdatedAt { get; set; }

            [JsonProperty("delay")]
            public object Delay { get; set; }

            [JsonProperty("followers")]
            public int Followers { get; set; }

            [JsonProperty("profile_banner")]
            public string ProfileBanner { get; set; }

            [JsonProperty("profile_banner_background_color")]
            public string ProfileBannerBackgroundColor { get; set; }

            [JsonProperty("views")]
            public int Views { get; set; }

            [JsonProperty("language")]
            public string Language { get; set; }
        }

        internal class Follow
        {

            [JsonProperty("created_at")]
            public string CreatedAt { get; set; }

            [JsonProperty("_links")]
            public Links Links { get; set; }

            [JsonProperty("notifications")]
            public bool Notifications { get; set; }

            [JsonProperty("channel")]
            public Channel Channel { get; set; }
        }

        internal class Links3
        {

            [JsonProperty("self")]
            public string Self { get; set; }

            [JsonProperty("next")]
            public string Next { get; set; }
        }

    }

    namespace CouchTwitch
    {

        internal class Follows
        {

            [JsonProperty("follows")]
            public Follow[] FollowsChannel { get; set; }

            [JsonProperty("_total")]
            public int Total { get; set; }

            [JsonProperty("_links")]
            public Links3 Links { get; set; }
        }

    }
}
