using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CouchTwitch
{
    // Generated by Xamasoft JSON Class Generator
    // http://www.xamasoft.com/json-class-generator

    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using CouchTwitch.UserJsonTypes;

    namespace CouchTwitch.UserJsonTypes
    {

        internal class Links
        {

            [JsonProperty("self")]
            public string Self { get; set; }
        }

        internal class Notifications
        {

            [JsonProperty("push")]
            public bool Push { get; set; }

            [JsonProperty("email")]
            public bool Email { get; set; }
        }

    }

    namespace CouchTwitch
    {

        internal class User
        {

            [JsonProperty("display_name")]
            public string DisplayName { get; set; }

            [JsonProperty("_id")]
            public int Id { get; set; }

            [JsonProperty("name")]
            public string Name { get; set; }

            [JsonProperty("type")]
            public string Type { get; set; }

            [JsonProperty("bio")]
            public object Bio { get; set; }

            [JsonProperty("created_at")]
            public string CreatedAt { get; set; }

            [JsonProperty("updated_at")]
            public string UpdatedAt { get; set; }

            [JsonProperty("logo")]
            public object Logo { get; set; }

            [JsonProperty("_links")]
            public Links Links { get; set; }

            [JsonProperty("email")]
            public string Email { get; set; }

            [JsonProperty("partnered")]
            public bool Partnered { get; set; }

            [JsonProperty("notifications")]
            public Notifications Notifications { get; set; }
        }

    }

}
